export type EngineMessageClassification = "prompt" | "event" | "internal";

export const PINNED_MESSAGE_CLASSIFICATION = {
  1: "event",
  2: "event",
  3: "internal",
  4: "event",
  5: "event",
  6: "internal",
  7: "internal",
  8: "internal",
  10: "prompt",
  11: "prompt",
  12: "prompt",
  13: "prompt",
  14: "prompt",
  15: "prompt",
  16: "prompt",
  18: "prompt",
  19: "prompt",
  20: "prompt",
  21: "prompt",
  22: "prompt",
  23: "prompt",
  24: "prompt",
  25: "prompt",
  26: "prompt",
  30: "event",
  31: "event",
  32: "event",
  33: "event",
  34: "internal",
  35: "event",
  36: "event",
  37: "event",
  38: "event",
  39: "event",
  40: "event",
  41: "event",
  42: "event",
  50: "event",
  53: "event",
  54: "event",
  55: "event",
  56: "event",
  60: "event",
  61: "internal",
  62: "event",
  63: "internal",
  64: "event",
  65: "internal",
  70: "event",
  71: "event",
  72: "event",
  73: "event",
  74: "event",
  75: "event",
  76: "event",
  80: "event",
  81: "event",
  83: "event",
  90: "event",
  91: "event",
  92: "event",
  93: "event",
  94: "event",
  96: "event",
  97: "event",
  100: "event",
  101: "event",
  102: "event",
  110: "event",
  111: "event",
  112: "event",
  113: "internal",
  114: "internal",
  120: "event",
  121: "internal",
  122: "internal",
  123: "internal",
  130: "event",
  131: "event",
  132: "prompt",
  133: "event",
  140: "prompt",
  141: "prompt",
  142: "prompt",
  143: "prompt",
  160: "event",
  161: "event",
  162: "event",
  163: "event",
  164: "event",
  165: "event",
  170: "event",
  180: "event",
  190: "event",
} as const satisfies Readonly<Record<number, EngineMessageClassification>>;

export const PINNED_MESSAGE_TYPES = Object.freeze(
  Object.keys(PINNED_MESSAGE_CLASSIFICATION).map(Number),
);

export function classifyEngineMessage(
  type: number,
): EngineMessageClassification {
  const classification = PINNED_MESSAGE_CLASSIFICATION[
    type as keyof typeof PINNED_MESSAGE_CLASSIFICATION
  ] as EngineMessageClassification | undefined;
  if (classification === undefined)
    throw new Error(`Unclassified pinned-core message type: ${type}`);
  return classification;
}
