export const REVIEW_PRESETS = [
  ["launcher-fresh", "Launcher · fresh"],
  ["launcher-progress", "Launcher · progress exists"],
  ["title-new", "Title · new player"],
  ["title-continue", "Title · Continue available"],
  ["load-standard", "Load · occupied/autosave/empty"],
  ["load-corrupt", "Load · incompatible/corrupt"],
  ["narrative-narration", "Narrative · narration"],
  ["narrative-dialogue", "Narrative · named dialogue / one character"],
  ["narrative-thought", "Narrative · protagonist thought"],
  ["narrative-two-characters", "Narrative · two characters"],
  ["narrative-long", "Narrative · long text / changed background"],
  ["narrative-missing", "Narrative · missing assets"],
  ["choice-default", "Choice · unresolved"],
  ["choice-resolved", "Choice · resolved"],
  ["history-empty", "History · empty"],
  ["history-entries", "History · entries"],
  ["settings-default", "Settings · unchanged"],
  ["settings-changed", "Settings · changed"],
  ["settings-reset", "Settings · reset"],
  ["settings-audio", "Settings · audio unavailable"],
  ["map-available", "Map · available"],
  ["map-locked", "Map · locked"],
  ["map-hidden", "Map · hidden"],
  ["map-completed", "Map · completed"],
  ["map-available-completed", "Map · available + completed"],
  ["prebattle-ready", "Pre-battle · ready / return / checkpoint"],
  ["battle-ready", "Battle mock · ready"],
  ["battle-win", "Battle mock · win"],
  ["battle-loss", "Battle mock · loss"],
  ["battle-abort", "Battle mock · abort"],
  ["battle-failure", "Battle mock · technical failure"],
  ["outcome-win", "Outcome · win branch"],
  ["outcome-loss", "Outcome · loss branch"],
  ["outcome-recovery", "Outcome · recovery branch"],
  ["reward-new", "Reward · new reward"],
  ["reward-acknowledged", "Reward · acknowledged / updated map"],
  ["save-idle", "Save · idle"],
  ["save-saving", "Save · saving"],
  ["save-success", "Save · success"],
  ["save-overwrite", "Save · overwrite"],
  ["save-failure", "Save · failure"],
  ["motion-default", "Motion · default"],
  ["motion-reduced", "Motion · reduced"],
] as const;

export type ReviewPreset = (typeof REVIEW_PRESETS)[number][0];
