export const EngineProcess = {
  END: 0,
  WAITING: 1,
  CONTINUE: 2,
} as const;

export const EngineLocation = {
  DECK: 1,
  HAND: 2,
  MONSTER: 4,
  SPELL_TRAP: 8,
  GRAVEYARD: 16,
  BANISHED: 32,
  EXTRA: 64,
  OVERLAY: 128,
  FIELD: 256,
  PENDULUM: 512,
} as const;

export const EnginePosition = {
  FACE_UP_ATTACK: 1,
  FACE_DOWN_ATTACK: 2,
  FACE_UP_DEFENSE: 4,
  FACE_DOWN_DEFENSE: 8,
} as const;

export const EngineDuelFlag = {
  PSEUDO_SHUFFLE: 0x10n,
  MODE_MR5: 0x2e800n,
} as const;

export const EngineQueryFlag = {
  CODE: 0x1,
  POSITION: 0x2,
  OWNER: 0x40000,
  IS_PUBLIC: 0x100000,
  OVERLAY_CARD: 0x10000,
  IS_HIDDEN: 0x1000000,
} as const;

export const EngineMessageType = {
  RETRY: 1,
  HINT: 2,
  START: 4,
  WIN: 5,
  SELECT_BATTLE_COMMAND: 10,
  SELECT_IDLE_COMMAND: 11,
  SELECT_EFFECT_YES_NO: 12,
  SELECT_YES_NO: 13,
  SELECT_OPTION: 14,
  SELECT_CARD: 15,
  SELECT_CHAIN: 16,
  SELECT_PLACE: 18,
  SELECT_POSITION: 19,
  SELECT_TRIBUTE: 20,
  SORT_CHAIN: 21,
  SELECT_COUNTER: 22,
  SELECT_SUM: 23,
  SELECT_DISABLED_FIELD: 24,
  SORT_CARD: 25,
  SELECT_UNSELECT_CARD: 26,
  SHUFFLE_DECK: 32,
  SHUFFLE_HAND: 33,
  NEW_TURN: 40,
  NEW_PHASE: 41,
  MOVE: 50,
  POSITION_CHANGE: 53,
  SET: 54,
  SUMMONING: 60,
  SPECIAL_SUMMONING: 62,
  FLIP_SUMMONING: 64,
  CHAINING: 70,
  CHAINED: 71,
  CHAIN_SOLVING: 72,
  CHAIN_SOLVED: 73,
  CHAIN_END: 74,
  CHAIN_NEGATED: 75,
  CHAIN_DISABLED: 76,
  DRAW: 90,
  DAMAGE: 91,
  RECOVER: 92,
  LIFE_POINTS_UPDATE: 94,
  PAY_LIFE_POINTS: 100,
  ATTACK: 110,
  BATTLE: 111,
  ROCK_PAPER_SCISSORS: 132,
  ANNOUNCE_RACE: 140,
  ANNOUNCE_ATTRIBUTE: 141,
  ANNOUNCE_CARD: 142,
  ANNOUNCE_NUMBER: 143,
} as const;

export const EngineResponseType = {
  SELECT_BATTLE_COMMAND: 0,
  SELECT_IDLE_COMMAND: 1,
  SELECT_EFFECT_YES_NO: 2,
  SELECT_YES_NO: 3,
  SELECT_OPTION: 4,
  SELECT_CARD: 5,
  SELECT_CARD_CODES: 6,
  SELECT_UNSELECT_CARD: 7,
  SELECT_CHAIN: 8,
  SELECT_DISABLED_FIELD: 9,
  SELECT_PLACE: 10,
  SELECT_POSITION: 11,
  SELECT_TRIBUTE: 12,
  SELECT_COUNTER: 13,
  SELECT_SUM: 14,
  SORT_CARD: 15,
  ANNOUNCE_RACE: 16,
  ANNOUNCE_ATTRIBUTE: 17,
  ANNOUNCE_CARD: 18,
  ANNOUNCE_NUMBER: 19,
  ROCK_PAPER_SCISSORS: 20,
} as const;

export const EngineIdleAction = {
  SUMMON: 0,
  SPECIAL_SUMMON: 1,
  CHANGE_POSITION: 2,
  SET_MONSTER: 3,
  SET_SPELL_TRAP: 4,
  ACTIVATE: 5,
  BATTLE_PHASE: 6,
  END_PHASE: 7,
  SHUFFLE: 8,
} as const;

export const EngineBattleAction = {
  ACTIVATE: 0,
  ATTACK: 1,
  MAIN_PHASE_2: 2,
  END_PHASE: 3,
} as const;

export const EnginePhase = {
  DRAW: 1,
  STANDBY: 2,
  MAIN_1: 4,
  BATTLE_START: 8,
  BATTLE_STEP: 16,
  DAMAGE: 32,
  DAMAGE_CALCULATION: 64,
  BATTLE: 128,
  MAIN_2: 256,
  END: 512,
} as const;
